-- =============================================
-- 校园"今天吃什么"随机大转盘 + 毒舌点评网
-- 达梦 DM8 数据库初始化脚本（终审封板生产级）
-- =============================================

-- =============================================
-- 1. 用户表
-- =============================================
CREATE TABLE T_APP_USER (
    ID              BIGINT IDENTITY(1,1) NOT NULL,
    NICKNAME        VARCHAR(50)   NOT NULL,
    STUDENT_ID      VARCHAR(30),
    AVATAR_URL      VARCHAR(500),
    USER_PWD        VARCHAR(200)  NOT NULL,
    USER_ROLE       VARCHAR(20)   DEFAULT 'STUDENT',
    ACCOUNT_STATUS  VARCHAR(20)   DEFAULT 'ACTIVE',
    LAST_LOGIN_TIME TIMESTAMP,
    CREATE_TIME     TIMESTAMP     DEFAULT SYSDATE,
    UPDATE_TIME     TIMESTAMP     DEFAULT SYSDATE,
    PRIMARY KEY (ID)
);

COMMENT ON TABLE  T_APP_USER IS '用户表 —— 支持一键投胎免密注册 + 传统学号登录双通道';
COMMENT ON COLUMN T_APP_USER.ID              IS '主键ID（达梦 IDENTITY 自增，由 DB 完全接管）';
COMMENT ON COLUMN T_APP_USER.NICKNAME        IS '花名/昵称（一键投胎随机生成，全站唯一）';
COMMENT ON COLUMN T_APP_USER.STUDENT_ID      IS '学号（可选，传统登录用；一键投胎用户可为空）';
COMMENT ON COLUMN T_APP_USER.AVATAR_URL      IS '头像地址';
COMMENT ON COLUMN T_APP_USER.USER_PWD        IS '加密密码(bcrypt)；一键投胎默认 EatOrNot666；规避 PASSWORD 保留字';
COMMENT ON COLUMN T_APP_USER.USER_ROLE       IS '角色:STUDENT/ADMIN —— 规避 ROLE 保留字';
COMMENT ON COLUMN T_APP_USER.ACCOUNT_STATUS  IS '状态:ACTIVE/BANNED —— 规避 STATUS 保留字';
COMMENT ON COLUMN T_APP_USER.LAST_LOGIN_TIME IS '最近登录时间';
COMMENT ON COLUMN T_APP_USER.CREATE_TIME     IS '创建时间';
COMMENT ON COLUMN T_APP_USER.UPDATE_TIME     IS '更新时间';

CREATE UNIQUE INDEX IDX_USER_NICKNAME   ON T_APP_USER(NICKNAME);
CREATE UNIQUE INDEX IDX_USER_STUDENT_ID ON T_APP_USER(STUDENT_ID);

-- =============================================
-- 2. 菜品档口表
-- =============================================
CREATE TABLE T_CAMPUS_DISH (
    ID              BIGINT IDENTITY(1,1) NOT NULL,
    DISH_NAME       VARCHAR(100)  NOT NULL,
    STALL_NAME      VARCHAR(100)  NOT NULL,
    CANTEEN_NAME    VARCHAR(100)  NOT NULL,
    FLOOR_NUM       INT           DEFAULT 1,
    PRICE           DECIMAL(10,2) DEFAULT 0.00,
    IMAGE_URL       VARCHAR(500),
    AVG_RATING      DECIMAL(3,2)  DEFAULT 0.00,
    REVIEW_COUNT    INT           DEFAULT 0,
    WEIGHT_FACTOR   DECIMAL(5,2)  DEFAULT 1.00,
    DISH_STATUS     VARCHAR(20)   DEFAULT 'ACTIVE',
    SUBMIT_USER_ID  BIGINT,
    CREATE_TIME     TIMESTAMP     DEFAULT SYSDATE,
    UPDATE_TIME     TIMESTAMP     DEFAULT SYSDATE,
    PRIMARY KEY (ID)
);

COMMENT ON TABLE  T_CAMPUS_DISH IS '菜品档口表';
COMMENT ON COLUMN T_CAMPUS_DISH.ID             IS '主键ID';
COMMENT ON COLUMN T_CAMPUS_DISH.DISH_NAME      IS '菜品名称';
COMMENT ON COLUMN T_CAMPUS_DISH.STALL_NAME     IS '档口名称';
COMMENT ON COLUMN T_CAMPUS_DISH.CANTEEN_NAME   IS '所属食堂';
COMMENT ON COLUMN T_CAMPUS_DISH.FLOOR_NUM      IS '所在楼层';
COMMENT ON COLUMN T_CAMPUS_DISH.PRICE          IS '价格';
COMMENT ON COLUMN T_CAMPUS_DISH.IMAGE_URL      IS '菜品图片地址';
COMMENT ON COLUMN T_CAMPUS_DISH.AVG_RATING     IS '平均评分(1-5)';
COMMENT ON COLUMN T_CAMPUS_DISH.REVIEW_COUNT   IS '评论总数';
COMMENT ON COLUMN T_CAMPUS_DISH.WEIGHT_FACTOR  IS '转盘权重系数';
COMMENT ON COLUMN T_CAMPUS_DISH.DISH_STATUS    IS '状态:ACTIVE/HIDDEN —— 规避 STATUS 保留字';
COMMENT ON COLUMN T_CAMPUS_DISH.SUBMIT_USER_ID IS '提交者用户ID';
COMMENT ON COLUMN T_CAMPUS_DISH.CREATE_TIME    IS '创建时间';
COMMENT ON COLUMN T_CAMPUS_DISH.UPDATE_TIME    IS '更新时间';

CREATE INDEX IDX_DISH_CANTEEN ON T_CAMPUS_DISH(CANTEEN_NAME, FLOOR_NUM);
CREATE INDEX IDX_DISH_RATING  ON T_CAMPUS_DISH(AVG_RATING DESC);

-- =============================================
-- 3. 毒舌评论表
-- =============================================
CREATE TABLE T_DISH_COMMENT (
    ID              BIGINT IDENTITY(1,1) NOT NULL,
    DISH_ID         BIGINT        NOT NULL,
    USER_ID         BIGINT        NOT NULL,
    RATING          INT           NOT NULL,
    CONTENT         VARCHAR(2000),
    ROAST_TEXT      VARCHAR(500),
    COMMENT_TAGS    VARCHAR(200),
    IS_ANONYMOUS    INT           DEFAULT 0,
    LIKE_COUNT      INT           DEFAULT 0,
    REPORT_COUNT    INT           DEFAULT 0,
    COMMENT_STATUS  VARCHAR(20)   DEFAULT 'ACTIVE',
    CREATE_TIME     TIMESTAMP     DEFAULT SYSDATE,
    PRIMARY KEY (ID)
);

COMMENT ON TABLE  T_DISH_COMMENT IS '毒舌评论表';
COMMENT ON COLUMN T_DISH_COMMENT.ID             IS '主键ID';
COMMENT ON COLUMN T_DISH_COMMENT.DISH_ID        IS '关联菜品ID';
COMMENT ON COLUMN T_DISH_COMMENT.USER_ID        IS '评论者用户ID';
COMMENT ON COLUMN T_DISH_COMMENT.RATING         IS '评分(1-5)';
COMMENT ON COLUMN T_DISH_COMMENT.CONTENT        IS '评论内容';
COMMENT ON COLUMN T_DISH_COMMENT.ROAST_TEXT     IS '系统生成的毒舌文案';
COMMENT ON COLUMN T_DISH_COMMENT.COMMENT_TAGS   IS '标签(逗号分隔):黑暗料理/性价比战神/排队王/食堂刺客';
COMMENT ON COLUMN T_DISH_COMMENT.IS_ANONYMOUS   IS '是否匿名:0-否,1-是';
COMMENT ON COLUMN T_DISH_COMMENT.LIKE_COUNT     IS '点赞数';
COMMENT ON COLUMN T_DISH_COMMENT.REPORT_COUNT   IS '被举报次数';
COMMENT ON COLUMN T_DISH_COMMENT.COMMENT_STATUS IS '状态:ACTIVE/HIDDEN/DELETED —— 规避 STATUS 保留字';
COMMENT ON COLUMN T_DISH_COMMENT.CREATE_TIME    IS '创建时间';

CREATE INDEX IDX_COMMENT_DISH   ON T_DISH_COMMENT(DISH_ID);
CREATE INDEX IDX_COMMENT_USER   ON T_DISH_COMMENT(USER_ID);
CREATE INDEX IDX_COMMENT_REPORT ON T_DISH_COMMENT(REPORT_COUNT DESC, COMMENT_STATUS);

-- =============================================
-- 4. 花名生成词库表
-- =============================================
CREATE TABLE T_NICKNAME_POOL (
    ID          BIGINT IDENTITY(1,1) NOT NULL,
    ADJECTIVE   VARCHAR(50) NOT NULL,
    FOOD_NAME   VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
);

COMMENT ON TABLE  T_NICKNAME_POOL IS '花名生成词库表';
COMMENT ON COLUMN T_NICKNAME_POOL.ADJECTIVE IS '形容词:暴躁的/emo的/摆烂的/怀民亦未寝的';
COMMENT ON COLUMN T_NICKNAME_POOL.FOOD_NAME IS '食物名:黄焖鸡/麻辣香锅/螺蛳粉/奶茶';

INSERT INTO T_NICKNAME_POOL(ADJECTIVE, FOOD_NAME) VALUES
('暴躁的', '黄焖鸡'), ('emo的', '麻辣香锅'), ('摆烂的', '螺蛳粉'),
('怀民亦未寝的', '烤冷面'), ('45度角的', '奶茶'), ('纯爱的', '炸鸡排'),
('绝绝子的', '石锅拌饭'), ('社恐的', '麻辣烫'), ('带带', '大师兄'),
('小丑', '竟是我自己'), ('重生之我是', '食堂阿姨'), ('早八', '困死我了'),
('学分', '绩点杀手'), ('体测', '及格线'), ('宿舍', '守夜人');

-- =============================================
-- 5. 用户投稿/意见反馈表
-- =============================================
CREATE TABLE T_SUGGESTION (
    ID              BIGINT IDENTITY(1,1) NOT NULL,
    USER_ID         BIGINT        NOT NULL,
    NICKNAME        VARCHAR(50)   NOT NULL,
    SUGG_TYPE       VARCHAR(20)   NOT NULL,
    CONTENT         VARCHAR(2000) NOT NULL,
    SUGG_STATUS     VARCHAR(20)   DEFAULT 'PENDING',
    ADMIN_NOTE      VARCHAR(500),
    CREATE_TIME     TIMESTAMP     DEFAULT SYSDATE,
    PRIMARY KEY (ID)
);

COMMENT ON TABLE  T_SUGGESTION IS '用户投稿/意见反馈表';
COMMENT ON COLUMN T_SUGGESTION.ID          IS '主键ID';
COMMENT ON COLUMN T_SUGGESTION.USER_ID     IS '投稿者用户ID';
COMMENT ON COLUMN T_SUGGESTION.NICKNAME    IS '投稿者花名';
COMMENT ON COLUMN T_SUGGESTION.SUGG_TYPE   IS '类型:FEEDBACK/SUGGEST/NEW_DISH';
COMMENT ON COLUMN T_SUGGESTION.CONTENT     IS '投稿内容';
COMMENT ON COLUMN T_SUGGESTION.SUGG_STATUS IS '状态:PENDING/REVIEWED/CLOSED';
COMMENT ON COLUMN T_SUGGESTION.ADMIN_NOTE  IS '管理员备注';
COMMENT ON COLUMN T_SUGGESTION.CREATE_TIME IS '创建时间';

CREATE INDEX IDX_SUGG_USER   ON T_SUGGESTION(USER_ID);
CREATE INDEX IDX_SUGG_STATUS ON T_SUGGESTION(SUGG_STATUS);
